<a href="https://colab.research.google.com/github/Despoka/Desain-Analisis-dan-Algoritma/blob/main/DAA_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DAA Week 3 14 September 2022

In [1]:
import numpy as np

In [2]:
aList = ["John", 33, "Toronto", True, 3.5]
print(aList)

['John', 33, 'Toronto', True, 3.5]


In [3]:
dataIdentitas = ["Nabiel Fauzan Ramadhan", 2021071006, "Informatika", "Desain Analisis Algoritma", "14/9/2022", "Universitas Pembangunan Jaya"] 
print(dataIdentitas)

['Nabiel Fauzan Ramadhan', 2021071006, 'Informatika', 'Desain Analisis Algoritma', '14/9/2022', 'Universitas Pembangunan Jaya']


In [4]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [5]:
dataIdentitas[1]

2021071006

In [6]:
dataIdentitas[5]

'Universitas Pembangunan Jaya'

In [7]:
bin_colors[1:3]

['Green', 'Blue']

In [8]:
dataIdentitas[1:3]

[2021071006, 'Informatika']

In [9]:
for aColor in bin_colors:
  print(aColor + "Square")

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [10]:
for biodata in dataIdentitas:
  print ("UPJ ",biodata)

UPJ  Nabiel Fauzan Ramadhan
UPJ  2021071006
UPJ  Informatika
UPJ  Desain Analisis Algoritma
UPJ  14/9/2022
UPJ  Universitas Pembangunan Jaya


In [11]:
#Tuple
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [12]:
bin_colors[2:]

('Blue', 'Yellow')

In [13]:
UPJ=('Universitas','Pembangunan','Jaya')
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [14]:
nested_tuple=((100),(200,400,600),(300),(400,800))
nested_tuple[1]

(200, 400, 600)

In [15]:
bin_colors={"manual_color":"Yellow","approved_color":"Green","refused_color":"Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [16]:
bin_colors.get('approved_color')

'Green'

In [17]:
bin_colors['approved_color']

'Green'

In [18]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [19]:
dataMahasiswa={'nama':"Nabiel Fauzan Ramadhan",'nim':'2021071006','prodi':'Informatika','universitas':'UPJ'}
print(dataMahasiswa)

{'nama': 'Nabiel Fauzan Ramadhan', 'nim': '2021071006', 'prodi': 'Informatika', 'universitas': 'UPJ'}


In [20]:
dataMahasiswa['nama']

'Nabiel Fauzan Ramadhan'

In [21]:
green = {'grass','leaves'}
print(green)

{'grass', 'leaves'}


In [22]:
green = {'grass','leaves','leaves'}
print(green)

{'grass', 'leaves'}


In [23]:
yellow = {'blood','leaves','fire hydrant','rose'}
red = {'dandelions','fire hydrant','leaves'}
print(yellow|red)
print(yellow&red)

{'fire hydrant', 'leaves', 'blood', 'dandelions', 'rose'}
{'fire hydrant', 'leaves'}


In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame ([['1','Fares',32,True],
                    ['2','Elena',23,False],
                    ['3','Steven',40,True]])

In [26]:
df.columns = ['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [27]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [28]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [29]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [30]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [31]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [32]:
bm = pd.DataFrame ([['1','Informatika',50,30,20],
                    ['2','Sistem Informasi',55,30,25],
                    ['3','Teknik Sipil',40,30,10]])
bm.columns = ['id','prodi','total','pria','wanita']
bm

id             prodi  total  pria  wanita
0  1       Informatika     50    30      20
1  2  Sistem Informasi     55    30      25
2  3      Teknik Sipil     40    30      10

In [33]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [34]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [35]:
latMatrix = np.array([[100, 200, 300],[700,600,500],[900,1000,800]])
latMatrix_transpose = latMatrix.transpose()
print(latMatrix)
print(f'Matrix Transpose:\n{latMatrix_transpose}')

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Matrix Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [36]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [37]:
print(type(myVector))

<class 'list'>


In [38]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [39]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [40]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [41]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [42]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [43]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
